config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  resources :users do
    member do
     get :following, :followers
    end
  end
  
  resources :relationships,       only: [:create, :destroy]
  resources :papers
  root 'papers#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/paper.rb
class Paper < ApplicationRecord
    belongs_to :user
end

app/models/relationship.rb
class Relationship < ApplicationRecord

    belongs_to :follower, class_name: "User"
    belongs_to :following, class_name: "User"
    validates :follower_id, presence: true
    validates :following_id, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :papers, dependent: :destroy
  validates :name, presence: true
  validates :profile, length: { maximum: 200 }

  has_many :following_relationships, foreign_key: "follower_id", class_name: "Relationship", dependent: :destroy
  has_many :followings, through: :following_relationships
  has_many :follower_relationships, foreign_key: "following_id", class_name: "Relationship", dependent: :destroy
  has_many :followers, through: :follower_relationships

  def following?(other_user)
    following_relationships.find_by(following_id: other_user.id)
  end

  def follow!(other_user)
    following_relationships.create!(following_id: other_user.id)
  end

  def unfollow!(other_user)
    following_relationships.find_by(following_id: other_user.id).destroy
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected
    def configure_permitted_parameters    # サインアップ時にnameのストロングパラメータを追加
        devise_parameter_sanitizer.permit(:sign_up, keys: [:name])   # アカウント編集の時にnameとprofileのストロングパラメータを追加
        devise_parameter_sanitizer.permit(:account_update, keys: [:name, :profile])
    end
end

app/controllers/papers_controller.rb
class PapersController < ApplicationController

    before_action :authenticate_user!, only: [:new, :create]
    
    def index
      if params[:search].present?
        search = params[:search]
        @papers = Paper.joins(:user).where("title LIKE ? OR author LIKE ? OR year LIKE ? OR journal LIKE ? OR purpose LIKE ? OR method LIKE ? OR result LIKE ? " , "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%")
      else
        @papers = Paper.all
      end
        @papers = @papers.page(params[:page]).per(3)
    end

    def new
        @paper=Paper.new
    end

    def create
        paper = Paper.new(paper_params)
        paper.user_id = current_user.id
        if paper.save!
          redirect_to :action => "index"
        else
          redirect_to :action => "new"
        end
    end

    def show
        @paper = Paper.find(params[:id])
    end

    def edit
        @paper = Paper.find(params[:id])
    end

    def update
        paper = Paper.find(params[:id])
        if paper.update(paper_params)
          redirect_to :action => "show", :id => paper.id
        else
          redirect_to :action => "new"
        end
    end

    def destroy
        paper = Paper.find(params[:id])
        paper.destroy
        redirect_to action: :index
    end

    private
    def paper_params
      params.require(:paper).permit(:name, :title, :author, :year, :journal, :subject, :purpose, :method, :result)
    end

end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

    def create
        @user = User.find(params[:relationship][:following_id])
        current_user.follow!(@user)
        redirect_to @user
    end
    
    def destroy
        @user = Relationship.find(params[:id]).following
        current_user.unfollow!(@user)
        redirect_to @user
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show
        @user = User.find(params[:id]) 
    end

    def following
        @user  = User.find(params[:id])
        @users = @user.followings
        render 'show_follow'
    end
  
    def followers
      @user  = User.find(params[:id])
      @users = @user.followers
      render 'show_follower'
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/papers_helper.rb
module PapersHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper

    def current_user?(user)
        user == current_user
    end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>論文管理ツール</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
  <header>
   <div class=header-list">
    <ul>
     <% if user_signed_in? %>
      <li><%= button_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
     <% else %>
      <li><%= link_to "新規登録", new_user_registration_path %></li>
      <li><%= link_to "ログイン", new_user_session_path %></li>
     <% end %>
    </ul>
   </div>
  </header>
  <main>
   <%= yield %>
  </main>
  </body>
</html>

app/views/papers/edit.html.erb
<h1>論文管理ツール</h1>
<h3>編集</h3>

<%= form_for @paper do |f| %>
  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title, :size => 50 %>
  </div>

  <div class="field">
    <%= f.label :author %>
    <%= f.text_field :author, :size => 30 %>
  </div>

  <div class="field">
    <%= f.label :year %> 
    <%= f.text_field :year, :size => 10 %>
  </div>


  <div class="field">
    <%= f.label :journal %>
    <%= f.text_field :journal, :size => 20 %>
  </div>

  <div class="field">
    <%= f.label :subject %>
    <%= f.text_field :subject, :size => 30 %>
  </div>

  <div class="field">
    <%= f.label :Purpose  %>
    <%= f.text_area :purpose, :size => "60x2" %>
  </div>

  <div class="field">
    <%= f.label :Method  %>
    <%= f.text_area :method, :size => "60x2" %>
  </div>

  <div class="field">
    <%= f.label :Result  %>
    <%= f.text_area :result, :size => "60x2" %>
  </div>
    <%= f.submit "編集する" %>
    <p><%= link_to "Tweet一覧に戻る", papers_path %></p>
  <% end %>

app/views/papers/index.html.erb
<h1>論文管理ツール</h1>
<h3>論文一覧ページ</h3>
<h3>投稿を検索</h3>
 <%= form_tag({controller:"papers",action:"index"}, method: :get) do %>
  <%= text_field_tag :search %>
   <%= submit_tag '検索する'  %>
<% end %>

<br><%= link_to "新規論文へ", new_paper_path %>

<div class="tweets-container">
<% if user_signed_in? %>
  <%= link_to "マイページへ", user_path(current_user.id) %>
<% end %>
  <% @papers.each do |t| %>
    <%= page_entries_info @papers %>
    <div class="tweet">
    <% if user_signed_in? %>
      <br><%= link_to t.user.name, user_path(t.user.id) %>
    <% end %>
      <br><B>Title</B>:<%= t.title %>
      <br><B>Author</B>:<%= t.author %>
      <br><B>Year</B>:<%= t.year %>
      <br><B>Journal</B>:<%= t.journal %>
      <br><B>Subject</B>:<%= t.subject %>
      <br><B>Purpose</B>:<%= t.purpose %>
      <br><B>Method</B>:<%= t.method %>
      <br><B>Result</B>:<%= t.result %>
      <br><%= link_to "詳細", paper_path(t.id) %> 
      <% if user_signed_in? && current_user.id == t.user_id %>
      <%= link_to "編集する", edit_paper_path(t.id) %>
      <%= link_to "削除する", paper_path(t.id), method: :delete %>
    <% end %>

    </div>
   
  <% end %>
</div>
<%= paginate @papers %>

app/views/papers/new.html.erb
<h1>論文管理ツール</h1>
<h3>新規論文</h3>
<%= form_for @paper do |f| %>

    <div class="field">
      <%= f.label :title %>
      <%= f.text_field :title, :size => 50 %>
    </div>

    <div class="field">
      <%= f.label :author %>
      <%= f.text_field :author, :size => 30 %>
    </div>

    <div class="field">
      <%= f.label :year %>
      <%= f.text_field :year, :size => 10 %>
    </div>


    <div class="field">
      <%= f.label :journal %>
      <%= f.text_field :journal, :size => 20 %>
    </div>

    <div class="field">
      <%= f.label :subject %>
      <%= f.text_field :subject, :size => 30 %>
    </div>

    <div class="field">
      <%= f.label :Purpose  %>
      <%= f.text_area :purpose, :size => "60x2" %>
    </div>

    <div class="field">
      <%= f.label :Method  %>
      <%= f.text_area :method, :size => "60x2" %>
    </div>

    <div class="field">
      <%= f.label :Result  %>
      <%= f.text_area :result, :size => "60x2" %>
    </div>

    <%= f.submit "投稿する" %>
    <% end %>
    
    <%= link_to "一覧に戻る", papers_path %>

app/views/papers/show.html.erb
<h1>論文管理ツール</h1>
<h3>論文内容 詳細</h3>
<div class="paper">
  <p><%= @paper.user.email %></p>
  <p><%= @paper.name %></p>
  <p><%= @paper.title %></p>
  <p><%= @paper.author %></p>
  <p><%= @paper.year %></p>
  <p><%= @paper.journal %></p>
  <p><%= @paper.subject %></p>
  <p><%= @paper.purpose %></p>
  <p><%= @paper.method %></p>
  <p><%= @paper.result %></p>
</div>

<%= link_to "Tweet一覧に戻る", papers_path %>

app/views/users/_follow.html.erb
<%= form_for(current_user.following_relationships.build(following_id: @user.id)) do |f| %>
    <div><%= f.hidden_field :following_id %></div>
    <%= f.submit "Follow", class: "btn btn-large btn-primary follow-btn" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
<div id="follow_form">
<% if current_user.following?(@user) %>
  <%= render 'unfollow' %>
<% else %>
  <%= render 'follow' %>
<% end %>
</div>
<% end %>  

app/views/users/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.followings.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.following_relationships.find_by(following_id: @user.id), html: { method: :delete }) do |f| %>
    <%= f.submit "Unfollow", class: "btn btn-large follow-btn" %>
<% end %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<h1>users#show</h1>
<p>名前 : <%= @user.name %></p>
<p>メールアドレス : <%= @user.email %></p>
<p>プロフィール : <%= @user.profile %></p>

<% if current_user.id == @user.id %>
  <%= link_to "編集する", edit_user_registration_path %>
<% end %>

<%= render 'follow_form' %>
<%= render 'stats' %>

<h2>ユーザーの投稿一覧</h2>
<% @user.papers.each do |t| %>  
  <U><B><br><%= t.user.email %></B></U>
  <br><B>Title</B>:<%= t.title %>
  <br><B>Author</B>:<%= t.author %>
  <br><B>Year</B>:<%= t.year %>
  <br><B>Journal</B>:<%= t.journal %>
  <br><B>Subject</B>:<%= t.subject %>
  <br><B>Purpose</B>:<%= t.purpose %>
  <br><B>Method</B>:<%= t.method %>
  <br><B>Result</B>:<%= t.result %>
<% end %>


<%= link_to "Tweet一覧に戻る", papers_path %>

app/views/users/show_follow.html.erb
<% @user.followings.each do |user| %>
    <table>
    <tr>
      <td>  <%= user.name %> </td>
      <td><%= link_to '詳細', user_path(user) %></td>
    </tr>
    
    </table>
<% end %>

app/views/users/show_follower.html.erb
<% @user.followers.each do |user| %>
    <table>
    <tr>
      <td>  <%= user.name %> </td>
      <td><%= link_to '詳細', user_path(user) %></td>
    </tr>
    
    </table>
<% end %>